module.exports = {
  printWidth: 120,
  trailingComma: 'all',
  singleQuote: true,
  jsxBracketSameLine: true,
  semi: true,
  plugins: [require('@trivago/prettier-plugin-sort-imports')],
  importOrder: [
    '^react',
    '^(?!react)\\w+$',
    '^ui',
    '^@?\\w',
    '^@/?\\w',
    '^(@components)(/.*|$)',
    '^\\u0000',
    '^\\.\\.(?!/?$)',
    '^\\.\\./?$',
    '^\\./(?=.*/)(?!/?$)',
    '^\\.(?!/?$)',
    '^\\./?$',
    '^.+\\.?(css)$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
