import { useEffect, useState } from 'react';
import { Hydrate, QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Head from 'next/head';

import { GrowthBookProvider } from '@growthbook/growthbook-react';

import type { AppProps } from 'next/app';
import '../styles/globals.css';
import { growthbook } from '@/libs/growthBook';

export default function App({ Component, pageProps }: AppProps) {
  const [queryClient] = useState(() => new QueryClient());

  useEffect(() => {
    // Load features asynchronously when the app renders
    growthbook.loadFeatures();
  }, []);

  return (
    <>
      <Head>
        <title>KOT DEV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Hydrate state={pageProps.dehydratedState}>
          <GrowthBookProvider growthbook={growthbook}>
            <Component {...pageProps} />
          </GrowthBookProvider>
        </Hydrate>
      </QueryClientProvider>
    </>
  );
}
